#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ToDoList.Resource", IsApplication=true)]

namespace ToDoList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int addList = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int alertDate = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int alertReset = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int alertTime = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int colorText = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int deleteTask = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int dueDate = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int dueDateLbl = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int dueDateReset = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int editName = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int editText = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout2 = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout3 = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout5 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout6 = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int savedList = 2131099650;
			
			// aapt resource value: 0x7f060012
			public const int space1 = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int textView1 = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int toDoLabel = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int AddList = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int AlertDate = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int AlertLabel = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int AlertTime = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Delete = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int DueDateLabel = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int DueDateText = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int ExistingTasksLabel = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int NameLabel = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int Reset = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int ToDo = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
